// Copyright AStarship <https://astarship.net>.

#undef D_
#undef R_
#undef D_THIS
#undef A_TEST_BEGIN
#undef A_RUN_TEST
#undef D_RUN_TEST
#undef R_RUN_TEST
#undef D_PAUSE
#undef D_COUT
#undef D_COUT_NL
#undef D_LINEF
#undef D_COUT_ERROR
#undef D_COUT_OBJ
#undef D_COUT_FUNCTION
#undef D_COUT_FUNCTION_LINE
#undef D_COUT_ARRAY
#undef D_COUT_ARRAY_LINES
#undef D_COUT_STACK
#undef D_COUT_STRING
#undef D_COUT_MATRIX
#undef D_COUT_LIST
#undef D_COUT_LOOM
#undef D_COUT_TABLE
#undef D_COUT_MAP
#undef D_COUT_BOOK
#undef D_COUT_DIC
#undef D_ARRAY_SAVE
#undef D_ARY_FILL
#undef D_RAM_WIPE
#undef D_ARY_WIPE
#undef D_SCK_WIPE
#undef D_STR_WIPE
#undef D_OBJ_WIPE
#undef A_CHECK
#undef D_CHECK
#undef R_CHECK
#undef A_COMPARE
#undef D_COMPARE
#undef R_COMPARE
#undef D_ASSERT_INDEX
#undef A_ASSERT
#undef D_ASSERT
#undef R_ASSERT
#undef A_ASSERT_PTR
#undef D_ASSERT_PTR
#undef R_ASSERT_PTR
#undef A_AVOW
#undef D_AVOW
#undef R_AVOW
#undef A_AVOW_NOT
#undef D_AVOW_NOT
#undef R_AVOW_NOT
#undef A_AVOW_INDEX
#undef R_AVOW_INDEX
#undef D_AVOW_INDEX
#undef A_FAIL
#undef D_FAIL
#undef R_FAIL
#undef A_WARN
#undef D_WARN
#undef R_WARN
#undef A_RETURN
#undef D_RETURN
#undef R_RETURN
#undef D_RETURNT
#undef D_RETURN_PTR_ERROR
#undef D_RETURN_CPTR_ERROR
#undef D_RETURN_TPTR_ERROR
#undef A_RETURN_VALUE
#undef D_RETURN_VALUE
#undef R_RETURN_VALUE
#undef D_CHECK_PTR_RETURN_CODE
#undef D_CHECK_PTR_TRETURN
#undef D_CHECK_PTR_TRETURN2
#undef D_CHECK_CPTR_RETURN
#undef D_CHECK_TPTR_RETURN
#undef D_CHECK_PTR_RETURN_NIL
#undef SCRIPT2_FAIL
